services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432

  s3:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123

  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 8001:15672